### ISSUE TITLE
don't work download_blob

### ISSUE THREAD

**Issue by starostinEgor** [cloudyr/AzureStor#27] opened 2019-05-21 18:46 UTC
i create a connection to the blob container and using the function list_blobs(cont) I see the file that I want to download.
  Name Last-Modified Content-Length
1         logs_sql_db.xlsx          <NA>          22610
2 vacanceReserch/price.csv          <NA>       24575435
 after run the function 
download_blob(cont
              ,src = "vacanceReserch/price.csv"
              ,dest = "~/price2.csv"
              ,overwrite = T)
R hangs and does not download the file. moreover, if you go through the folders with your hands to the end point, I see that he created a file with zero size

function upload_blob(cont, src=pathFile, dest="vacanceReserch/price.csv") work perfect

**Comment by starostinEgor** [comment] 2019-05-21 19:12
after hours of work, I get an error
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Send failure: Connection was reset

**Comment by Hong-Revo** [comment] 2019-05-22 00:07
I can't reproduce this error. Can you try it again? The network connection may have been glitched.

**Comment by Hong-Revo** [comment] 2019-05-22 00:15
Also, you can try out the dev version which will retry failed transfers.

**Comment by starostinEgor** [comment] 2019-05-22 02:47
I use artical this: https://blog.revolutionanalytics.com/2018/11/azurer-intro.html
I can obtain them with devtools::install_github.
library(devtools)
install_github("cloudyr/AzureRMR")
install_github("cloudyr/AzureVM")
install_github("cloudyr/AzureStor")
install_github("cloudyr/AzureContainers")

**Comment by Hong-Revo** [comment] 2019-05-22 03:37
You probably had a network glitch. Try the download again.

**Comment by Hong-Revo** [comment] 2019-05-23 01:51
I'm going to close this since the main repo is moving to https://github.com/Azure/AzureStor and GH doesn't allow transferring issues across orgs. If the problem persists, you can open a new issue there.

**Closed by Hong-Revo** 2019-05-23 01:51 UTC
